name: krishi_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  camera: ^0.11.4
  curved_navigation_bar: ^1.0.6
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  geolocator: ^10.1.0
  google_fonts: ^8.0.2
  get: ^4.7.3
  http: ^1.6.0
  image: ^4.0.17
  image_picker: ^1.2.1
  latlong2: ^0.9.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^11.1.0
  shared_preferences: ^2.5.4
  tflite_flutter: ^0.12.1
  weather_icons: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite
    - assets/labels.txt
    - assets/disease_info.json
